Ignore __pycache__ from urgent_evidence example
casework/casework.github.io pull request #125
Opened 2021-09-22 19:57 UTC by balon

This QOL PR will adjust the gitignore file to ignore the __pycache__ folder in examples/urgent_evidence.

2021-09-22 20:06 UTC, balon commented
PR now addresses `*.swp` as well.

2021-09-22 20:39 UTC, ajnelson-nist requested changes

2021-09-22 20:39 UTC, ajnelson-nist commented on .gitignore
> +examples/urgent_evidence/__pycache__
@balon , can you see this comment?

2021-09-22 20:39 UTC, ajnelson-nist commented on .gitignore
> +examples/urgent_evidence/__pycache__
There's no reason to track `__pycache__` anywhere in this repository, so can this line drop the `examples/urgent_evidence/` part?

Also, can you please restore the end-of-file end-of-line?

2021-09-22 20:41 UTC, ajnelson-nist commented on .gitignore
> +examples/urgent_evidence/__pycache__
Updated!  Thank you!

2021-09-22 20:41 UTC, ajnelson-nist approved these changes

2021-09-23 01:32 UTC, regriff approved these changes

2021-09-23 01:32 UTC, merged