Create release page for CASE 0.2.1
casework/casework.github.io pull request #162
Opened 2022-04-01 10:36 UTC by plbt5

* Created new 0.2.1 directory in 'releases/'
* Updated 'releases.yml'

Apparently, modifications have also been made to 'dependencies/CASE-Utilities-Python', but not by me.

2022-04-01 14:13 UTC, ajnelson-nist requested changes
Also, the submodule pointer update should be reverted.

2022-04-01 14:13 UTC, ajnelson-nist commented on _data/releases/releases.yml
> +  date: 2022-04-01
This release hasn't been finished yet, so its date should be `TBD`.

2022-04-01 14:13 UTC, ajnelson-nist commented on releases/0.2.1/index.md
> +
@plbt5 , were you intending to list the first 0.2.1-specific proposal on this page?

2022-04-01 14:13 UTC, ajnelson-nist commented on releases/0.2.1/index.md
> +
Change Proposal 38 was applied in the history of the CASE `master` branch.  Can you add that to the 0.2.1 and 0.4.0 pages?  We apparently missed listing it as a change in 0.4.0.

2022-04-01 14:16 UTC, ajnelson-nist commented
I've corrected the submodule issue.

2022-04-25 20:11 UTC, regriff approved these changes

2022-04-25 20:14 UTC, regriff approved these changes

2022-04-25 20:17 UTC, ajnelson-nist approved these changes

2022-04-25 20:18 UTC, merged